// =============================================================
// CHEF'S TABLE CHECK-IN — Mock Data & Types
// Design: Dark Ops Dashboard — amber/gold accents, dark warm bg
// =============================================================

export type TicketTier = 1 | 2 | 3;
export type CheckInStatus = "checked-in" | "pending" | "no-show";

export interface Attendee {
  id: string;
  firstName: string;
  lastName: string;
  ticketTier: TicketTier;
  squad?: string;
  status: CheckInStatus;
  checkedInAt?: string;
  notes?: string;
}

export interface Location {
  id: string;
  name: string;
  chef: string;
  window: string; // e.g. "Friday Dinner"
  capacity: number;
  roster: Attendee[];
}

// ---- Name Aliases (for fuzzy nickname matching) ----
export const NAME_ALIASES: Record<string, string[]> = {
  william: ["bill", "will", "billy", "willy", "liam"],
  robert: ["bob", "rob", "bobby", "robbie"],
  richard: ["rick", "dick", "rich", "ricky"],
  james: ["jim", "jimmy", "jamie"],
  john: ["johnny", "jon"],
  michael: ["mike", "mikey", "mick"],
  thomas: ["tom", "tommy"],
  charles: ["charlie", "chuck", "chas"],
  christopher: ["chris", "topher"],
  daniel: ["dan", "danny"],
  david: ["dave", "davy"],
  joseph: ["joe", "joey"],
  matthew: ["matt", "matty"],
  anthony: ["tony", "ant"],
  donald: ["don", "donnie"],
  steven: ["steve", "stevie"],
  stephen: ["steve", "stevie"],
  edward: ["ed", "eddie", "ned", "ted"],
  george: ["georgie"],
  henry: ["hank", "harry"],
  harold: ["harry", "hal"],
  kenneth: ["ken", "kenny"],
  lawrence: ["larry", "lars"],
  leonard: ["len", "lenny"],
  nicholas: ["nick", "nicky", "nico"],
  patrick: ["pat", "patty"],
  peter: ["pete"],
  philip: ["phil"],
  raymond: ["ray"],
  ronald: ["ron", "ronnie"],
  samuel: ["sam", "sammy"],
  timothy: ["tim", "timmy"],
  walter: ["walt", "wally"],
  elizabeth: ["liz", "beth", "betty", "eliza", "lisa", "ellie", "bette"],
  margaret: ["maggie", "meg", "peggy", "marge"],
  patricia: ["pat", "patty", "tricia"],
  barbara: ["barb", "barbie"],
  jennifer: ["jen", "jenny"],
  linda: ["lin", "lindy"],
  dorothy: ["dot", "dottie"],
  susan: ["sue", "suzy"],
  jessica: ["jess", "jessie"],
  sarah: ["sara"],
  karen: ["kari"],
  nancy: ["nan"],
  betty: ["beth", "bette"],
  helen: ["nell", "nellie"],
  sandra: ["sandy"],
  donna: ["don"],
  carol: ["carrie"],
  ruth: [],
  sharon: ["sherry"],
  michelle: ["shelly", "mich"],
  laura: ["laurie"],
  kimberly: ["kim", "kimmy"],
  deborah: ["deb", "debbie"],
  stephanie: ["steph"],
  catherine: ["cat", "cathy", "kate", "katie", "kathy"],
  katherine: ["cat", "cathy", "kate", "katie", "kathy"],
  virginia: ["ginny", "ginger"],
  rebecca: ["becca", "becky"],
  judith: ["judy", "judi"],
  jacqueline: ["jackie", "jacqui"],
  diane: ["di"],
  alice: ["ali"],
  ann: ["annie", "anna"],
  anne: ["annie", "anna"],
  grace: [],
  victoria: ["vicky", "tori"],
  amanda: ["mandy"],
  melissa: ["mel", "missy"],
  debra: ["deb", "debbie"],
  angela: ["angie"],
  brenda: [],
  emma: ["em"],
  abigail: ["abby", "abbie"],
  madison: ["maddie", "maddy"],
  olivia: ["liv", "livvy"],
  sophia: ["sophie"],
  isabella: ["bella", "izzy"],
  mia: [],
  charlotte: ["charlie", "lottie"],
  amelia: ["amy", "millie"],
  evelyn: ["evie"],
  harper: [],
  avery: [],
  emily: ["em"],
  ella: [],
  scarlett: [],
  aria: [],
  luna: [],
  chloe: [],
  penelope: ["penny"],
  layla: [],
  riley: [],
  zoey: ["zoe"],
  nora: ["norah"],
  lily: [],
  eleanor: ["ellie", "nell", "nora"],
  hannah: [],
  lillian: ["lily", "lilly"],
  addison: ["addie"],
  aubrey: [],
  ellie: ["eleanor", "ella"],
  stella: [],
  natalie: ["nat"],
  zoe: ["zoey"],
  leah: [],
  hazel: [],
  violet: ["vi"],
  aurora: ["rory"],
  savannah: ["savvy"],
  audrey: [],
  brooklyn: ["brooke"],
  bella: ["isabella"],
  claire: [],
  skylar: ["sky"],
  lucy: [],
  paisley: [],
  everly: [],
  caroline: ["carrie", "carol"],
  nova: [],
  genesis: [],
  emilia: ["emily", "millie"],
  kennedy: ["ken"],
  samantha: ["sam", "sammy"],
  maya: ["mia"],
  willow: ["will"],
  kinsley: [],
  naomi: [],
  aaliyah: [],
  elena: ["ellie"],
  ariana: ["ari"],
  allison: ["allie"],
  gabriella: ["gabby", "gabi"],
};

// ---- Mock Location Rosters ----
export const MOCK_LOCATIONS: Location[] = [
  {
    id: "loc-001",
    name: "Atelier by Thomas Keller",
    chef: "Thomas Keller",
    window: "Friday Dinner",
    capacity: 80,
    roster: [
      { id: "a001", firstName: "William", lastName: "Harrington", ticketTier: 1, status: "pending" },
      { id: "a002", firstName: "Elizabeth", lastName: "Chen", ticketTier: 1, status: "pending", squad: "CORP-APEX" },
      { id: "a003", firstName: "Robert", lastName: "Vasquez", ticketTier: 2, status: "pending" },
      { id: "a004", firstName: "Margaret", lastName: "Okafor", ticketTier: 1, status: "pending" },
      { id: "a005", firstName: "Christopher", lastName: "Nakamura", ticketTier: 2, status: "pending", squad: "CORP-APEX" },
      { id: "a006", firstName: "Jennifer", lastName: "Russo", ticketTier: 3, status: "pending" },
      { id: "a007", firstName: "Michael", lastName: "Thornton", ticketTier: 1, status: "pending" },
      { id: "a008", firstName: "Patricia", lastName: "Delacroix", ticketTier: 2, status: "pending" },
      { id: "a009", firstName: "James", lastName: "O'Brien", ticketTier: 3, status: "pending" },
      { id: "a010", firstName: "Katherine", lastName: "Whitfield", ticketTier: 1, status: "pending" },
      { id: "a011", firstName: "David", lastName: "Moreau", ticketTier: 2, status: "pending", squad: "CORP-APEX" },
      { id: "a012", firstName: "Susan", lastName: "Fitzgerald", ticketTier: 3, status: "pending" },
      { id: "a013", firstName: "Thomas", lastName: "Bergmann", ticketTier: 1, status: "pending" },
      { id: "a014", firstName: "Barbara", lastName: "Kimura", ticketTier: 2, status: "pending" },
      { id: "a015", firstName: "Richard", lastName: "Castellano", ticketTier: 1, status: "pending" },
      { id: "a016", firstName: "Dorothy", lastName: "Patel", ticketTier: 3, status: "pending" },
      { id: "a017", firstName: "Charles", lastName: "Abernathy", ticketTier: 2, status: "pending" },
      { id: "a018", firstName: "Sandra", lastName: "Kowalski", ticketTier: 1, status: "pending" },
      { id: "a019", firstName: "Joseph", lastName: "Tremblay", ticketTier: 3, status: "pending" },
      { id: "a020", firstName: "Nancy", lastName: "Silverton", ticketTier: 1, status: "pending" },
    ],
  },
  {
    id: "loc-002",
    name: "Maison Kwame",
    chef: "Kwame Onwuachi",
    window: "Saturday Dinner",
    capacity: 80,
    roster: [
      { id: "b001", firstName: "Alexander", lastName: "Fontaine", ticketTier: 1, status: "pending" },
      { id: "b002", firstName: "Victoria", lastName: "Huang", ticketTier: 2, status: "pending" },
      { id: "b003", firstName: "Nicholas", lastName: "Reeves", ticketTier: 1, status: "pending" },
      { id: "b004", firstName: "Samantha", lastName: "Goldberg", ticketTier: 3, status: "pending" },
      { id: "b005", firstName: "Timothy", lastName: "Ashworth", ticketTier: 2, status: "pending" },
      { id: "b006", firstName: "Catherine", lastName: "Nguyen", ticketTier: 1, status: "pending" },
      { id: "b007", firstName: "Edward", lastName: "Larsson", ticketTier: 2, status: "pending" },
      { id: "b008", firstName: "Stephanie", lastName: "Mbeki", ticketTier: 3, status: "pending" },
      { id: "b009", firstName: "Daniel", lastName: "Kostadinov", ticketTier: 1, status: "pending" },
      { id: "b010", firstName: "Rebecca", lastName: "Winters", ticketTier: 2, status: "pending" },
      { id: "b011", firstName: "Anthony", lastName: "Delgado", ticketTier: 1, status: "pending" },
      { id: "b012", firstName: "Melissa", lastName: "Park", ticketTier: 3, status: "pending" },
    ],
  },
  {
    id: "loc-003",
    name: "Noma Pop-Up",
    chef: "René Redzepi",
    window: "Thursday Dinner",
    capacity: 80,
    roster: [
      { id: "c001", firstName: "Jonathan", lastName: "Blackwood", ticketTier: 1, status: "pending" },
      { id: "c002", firstName: "Olivia", lastName: "Marchetti", ticketTier: 1, status: "pending" },
      { id: "c003", firstName: "Matthew", lastName: "Sorensen", ticketTier: 2, status: "pending" },
      { id: "c004", firstName: "Isabella", lastName: "Ferreira", ticketTier: 1, status: "pending" },
      { id: "c005", firstName: "Lawrence", lastName: "Yamamoto", ticketTier: 3, status: "pending" },
      { id: "c006", firstName: "Abigail", lastName: "Thornton", ticketTier: 2, status: "pending" },
      { id: "c007", firstName: "Philip", lastName: "Osei", ticketTier: 1, status: "pending" },
      { id: "c008", firstName: "Jacqueline", lastName: "Beaumont", ticketTier: 2, status: "pending" },
    ],
  },
];
